export const properties =  [
   
    {
        "id": 10,
        "images": [
            {
                "id": 41,
                "house": 10,
                "image": "image/upload/v1650564997/bdcszns5rvr10n4ubcmq.jpg"
            },
            {
                "id": 42,
                "house": 10,
                "image": "image/upload/v1650565004/aagpfqhdiowngnf59n5c.jpg"
            },
            {
                "id": 43,
                "house": 10,
                "image": "image/upload/v1650565007/qvq6opsmhwmlkwtfvpcf.jpg"
            }
        ],
        "floors": "1",
        "beds": "2",
        "kitchen": "1",
        "living": "0",
        "parking": "3",
        "bath": "2",
        "province": "4",
        "title": "nice house",
        "slug": "nice-house",
        "description": "<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p><p><br>&nbsp;</p>",
        "road_to_property": "adsadadsdasdsd",
        "access_road": "asdads",
        "district": "dhading",
        "zone": "mechi",
        "zip": 1231231,
        "landmark": "this is a landmark",
        "ropani": 2,
        "aana": 3,
        "paisa": 1,
        "daam": 1,
        "price_in_number": 21313123,
        "price_in_words": "sdfsafsfdfasf",
        "price_negotiable": "Yes",
        "main_image": "image/upload/v1650564986/t5togv3a5qhvfyhhpqwq.jpg",
        "url": "https://youtu.be/iDS6p61VnWg",
        "latitude": 27.96727370212278,
        "longitude": 85.77490399073467,
        "created_at": "2022-04-22T00:01:27.907735+05:45",
        "updated_at": "2022-04-22T00:02:06.527924+05:45",
        "no_of_views": 0,
        "is_active": true,
        "per": "month",
        "seller": 1,
        "listing_type": "premium listing",
        "area": "dhur",
        "face_towards": "east",
        "status": "Up",
        "property_type": "House for rent",
        "condition": "brand new",
        "furnishing": "fully furnished",
        "house_type": "single family",
        "facility": [],
        "type": "house"
    },
    {
        "id": 11,
        "images": [
            {
                "id": 44,
                "house": 11,
                "image": "image/upload/v1650832351/grkcyivkduhpdc3iggpm.jpg"
            },
            {
                "id": 45,
                "house": 11,
                "image": "image/upload/v1650832356/yuk5rxxh2senuqcshl0p.jpg"
            },
            {
                "id": 46,
                "house": 11,
                "image": "image/upload/v1650832362/x7e4qdpofoaeghehbkns.jpg"
            },
            {
                "id": 47,
                "house": 11,
                "image": "image/upload/v1650832366/yohgxvfwvb4muvfsr5lc.jpg"
            }
        ],
        "floors": "1",
        "beds": "3",
        "kitchen": "2",
        "living": "0",
        "parking": "1",
        "bath": "1",
        "province": "4",
        "title": "a small but beautiful house",
        "slug": "a-small-but-beautiful-house",
        "description": "<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of \"de Finibus Bonorum et Malorum\" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, \"Lorem ipsum dolor sit amet..\", comes from a line in section 1.10.32.</p><p><br>&nbsp;</p>",
        "road_to_property": "thisis road that goes to property",
        "access_road": "this is acfcess road near prperty",
        "district": "rupandehi",
        "zone": "lumbini",
        "zip": 32907,
        "landmark": "near a pink colored school.",
        "ropani": 1,
        "aana": 2,
        "paisa": 3,
        "daam": 4,
        "price_in_number": 180000,
        "price_in_words": "one lakh eighty thousand",
        "price_negotiable": "Yes",
        "main_image": "image/upload/v1650832346/v7jwmxc9hdrkn0mjs3ze.png",
        "url": "https://www.youtube.com/watch?v=mk8Ks0Au46w",
        "latitude": 27.700829530158472,
        "longitude": 85.30214633398788,
        "created_at": "2022-04-25T02:17:27.612285+05:45",
        "updated_at": "2022-04-26T00:05:11.494171+05:45",
        "no_of_views": 0,
        "is_active": true,
        "per": "month",
        "seller": 4,
        "listing_type": "premium listing",
        "area": "ropani",
        "face_towards": "east",
        "status": "Up",
        "property_type": "House for rent",
        "condition": "brand new",
        "furnishing": "semi furnished",
        "house_type": "single family",
        "facility": [],
        "type": "house"
    },
    {
        "id": 9,
        "images": [
            {
                "id": 38,
                "house": 9,
                "image": "image/upload/v1650554204/sqnzh9g7j7zzwlhsmmqf.jpg"
            },
            {
                "id": 39,
                "house": 9,
                "image": "image/upload/v1650554211/icxiwub09kxopoesxpt5.jpg"
            },
            {
                "id": 40,
                "house": 9,
                "image": "image/upload/v1650554217/etghsfsz4anpchp1bf1a.jpg"
            }
        ],
        "floors": "2",
        "beds": "3",
        "kitchen": "1",
        "living": "0",
        "parking": "2",
        "bath": "1",
        "province": "2",
        "title": "zxczxsd asd sdf df dfs d df g",
        "slug": "zxczxsd-asd-sdf-df-dfs-d-df-g",
        "description": "<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p><p><br>&nbsp;</p>",
        "road_to_property": "sdfsfsfds",
        "access_road": "fsfdfsdfsfd",
        "district": "rupandehi",
        "zone": "lumbini",
        "zip": 12312,
        "landmark": "sfcsfsfsfds df sf sdf s",
        "ropani": 2,
        "aana": 3,
        "paisa": 1,
        "daam": 2,
        "price_in_number": 200000,
        "price_in_words": "three crore fifty laksa",
        "price_negotiable": "Yes",
        "main_image": "image/upload/v1650554195/qygwfqjaqdrkhkeunbeq.jpg",
        "url": "https://www.youtube.com/watch?v=Pf7g32CwX_s",
        "latitude": 28.25138960461761,
        "longitude": 85.92613692330701,
        "created_at": "2022-04-21T21:01:38.402559+05:45",
        "updated_at": "2022-04-21T21:32:31.629417+05:45",
        "no_of_views": 0,
        "is_active": true,
        "per": "year",
        "seller": 1,
        "listing_type": "top listing",
        "area": "katha",
        "face_towards": "east",
        "status": "Up",
        "property_type": "House for rent",
        "condition": "brand new",
        "furnishing": "semi furnished",
        "house_type": "single family",
        "facility": [],
        "type": "house"
    },
    {
        "id": 8,
        "images": [
            {
                "id": 32,
                "house": 8,
                "image": "image/upload/v1650221904/qsyiztyyr127y8ogyhrf.jpg"
            },
            {
                "id": 33,
                "house": 8,
                "image": "image/upload/v1650221915/fkxnl8bg1z58znh7frrj.jpg"
            },
            {
                "id": 34,
                "house": 8,
                "image": "image/upload/v1650221921/uazuqiqc0se8a8an8zv4.jpg"
            },
            {
                "id": 35,
                "house": 8,
                "image": "image/upload/v1650221925/qmb4yzzcoeoo7kgrxfxk.jpg"
            },
            {
                "id": 36,
                "house": 8,
                "image": "image/upload/v1650221930/ciaphdiogjuvlc8pwozo.jpg"
            },
            {
                "id": 37,
                "house": 8,
                "image": "image/upload/v1650221936/xc3ub5wzopy3oblcjga6.jpg"
            }
        ],
        "floors": "1",
        "beds": "2",
        "kitchen": "3",
        "living": "0",
        "parking": "2",
        "bath": "1",
        "province": "1",
        "title": "A beautiful villah",
        "slug": "a-beautiful-villah",
        "description": "<p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>",
        "road_to_property": "asdadasda",
        "access_road": "dasdadsdasds",
        "district": "2",
        "zone": "4",
        "zip": 123123,
        "landmark": "asdadasd",
        "ropani": 1,
        "aana": 2,
        "paisa": 3,
        "daam": 2,
        "price_in_number": 200000,
        "price_in_words": "two lakhs",
        "price_negotiable": "Yes",
        "main_image": "image/upload/v1650221896/iimlwdvcyibwcfmh7rsn.jpg",
        "url": "https://www.youtube.com/watch?v=Pf7g32CwX_s",
        "latitude": 26.51682302714633,
        "longitude": 85.80609475906174,
        "created_at": "2022-04-18T00:43:17.827585+05:45",
        "updated_at": "2022-04-21T22:24:35.328725+05:45",
        "no_of_views": 0,
        "is_active": true,
        "per": "month",
        "seller": 1,
        "listing_type": "top listing",
        "area": "sq. ft",
        "face_towards": "south",
        "status": "Up",
        "property_type": "House for rent",
        "condition": "brand new",
        "furnishing": "fully furnished",
        "house_type": "single family",
        "facility": [],
        "type": "house"
    },
    {
        "id": 2,
        "images": [
            {
                "id": 4,
                "land": 2,
                "image": "image/upload/v1650541955/jctsxjewuyvhjceqamgt.jpg"
            },
            {
                "id": 5,
                "land": 2,
                "image": "image/upload/v1650541961/oyle7a1vxqaftgm070p3.jpg"
            },
            {
                "id": 6,
                "land": 2,
                "image": "image/upload/v1650541966/ivy8m2ir2zuuysriajbm.jpg"
            }
        ],
        "province": "3",
        "title": "my land",
        "slug": "my-land",
        "description": "<ul><li><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</li></ul>",
        "road_to_property": "sdfsafsfdad",
        "access_road": "adsadasdasdad",
        "district": "1",
        "zone": "3",
        "zip": 12343,
        "landmark": "dfgdgfdg",
        "ropani": 1,
        "aana": 2,
        "paisa": 3,
        "daam": 2,
        "price_in_number": 20000000,
        "price_in_words": "two crores only",
        "price_negotiable": "No",
        "main_image": "image/upload/v1650541948/v4lc4zomgcfajxbjc013.jpg",
        "url": "https://www.youtube.com/watch?v=Pf7g32CwX_s",
        "latitude": 28.170746411118273,
        "longitude": 85.96545105512351,
        "created_at": "2022-04-21T17:37:29.104444+05:45",
        "updated_at": "2022-04-21T21:23:16.960094+05:45",
        "no_of_views": 0,
        "is_active": true,
        "seller": 1,
        "listing_type": "top listing",
        "area": "sq. ft",
        "face_towards": "east",
        "status": "Up",
        "type": "land"
    }
]