# Generated by Django 4.0.1 on 2022-01-16 07:49

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'facility',
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('Top Listing Rs.23600', 'TL'), ('Premium Listing Rs.17600', 'PL'), ('Featured Listing Rs.9600', 'FL')], max_length=100)),
                ('condition', models.CharField(blank=True, choices=[('Brand New', 'Brand New'), ('Used', 'Used')], max_length=100)),
                ('road_to_property', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Ropani', 'Ropani'), ('Sq,Ft', 'Sq.Ft'), ('Dhur', 'Dhur'), ('Kathha', 'Kathha'), ('Hath', 'Hath'), ('Bigha', 'Bigha')], max_length=100)),
                ('ropani', models.CharField(max_length=100)),
                ('aana', models.CharField(max_length=100)),
                ('paisa', models.CharField(max_length=100)),
                ('daam', models.CharField(max_length=100)),
                ('price_in_number', models.IntegerField(default=0)),
                ('price_in_words', models.CharField(max_length=200)),
                ('price_negitiable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('furnishing', models.CharField(blank=True, choices=[('Not Furnished', 'Not Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Full Furnished', 'Full Furnished')], max_length=50)),
                ('house_type', models.CharField(blank=True, choices=[('Flat System', 'Flat System'), ('Single Family', 'Single Family'), ('Commercial', 'Commercial'), ('Apartment Building', 'Apartment Building')], max_length=100)),
                ('face_towards', models.CharField(blank=True, choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South'), ('North-East', 'North-East'), ('South-East', 'Norht-West'), ('South-East', 'South-East'), ('South-West', 'South-West')], max_length=40)),
                ('floors', models.PositiveBigIntegerField(blank=True)),
                ('beds', models.PositiveBigIntegerField(blank=True)),
                ('kitchen', models.PositiveBigIntegerField(blank=True)),
                ('living', models.PositiveBigIntegerField(blank=True)),
                ('bath', models.PositiveBigIntegerField(blank=True)),
                ('property_main_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='property_sale/')),
                ('is_active', models.BooleanField(default=False)),
                ('facility', models.ManyToManyField(blank=True, related_name='facilities', to='p_sale.Facility')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_sale.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='property_sale/document/')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 1, 16, 13, 34, 29, 72603))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='p_sale.property')),
            ],
        ),
    ]
