# Generated by Django 4.0.1 on 2022-01-16 08:20

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 14, 5, 4, 933550)),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_main_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='main_image'),
        ),
    ]
