# Generated by Django 4.0.1 on 2022-03-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('p_sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='land',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.propertystatus'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.kycstatus'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='houseownercertificate',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_sale.house'),
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.areatype'),
        ),
        migrations.AddField(
            model_name='house',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.listingconditioin'),
        ),
        migrations.AddField(
            model_name='house',
            name='face_towards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.facetowards'),
        ),
        migrations.AddField(
            model_name='house',
            name='facility',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='p_sale.Facility'),
        ),
        migrations.AddField(
            model_name='house',
            name='furnishing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.furnishingtype'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='p_sale.housetype'),
        ),
        migrations.AddField(
            model_name='house',
            name='listing_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.listingtype'),
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_sale.propertytype'),
        ),
        migrations.AddField(
            model_name='house',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.propertystatus'),
        ),
        migrations.AddField(
            model_name='contactnum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionallandimage',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='p_sale.land'),
        ),
        migrations.AddField(
            model_name='additionalhouseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='p_sale.house'),
        ),
    ]
