# Generated by Django 4.0.1 on 2022-02-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.listingconditioin'),
        ),
    ]
