# Generated by Django 4.0.1 on 2022-01-16 08:20

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 14, 5, 44, 480307)),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='document_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='doc_img'),
        ),
    ]
