# Generated by Django 4.0.1 on 2022-03-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0003_houseownercertificate_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnum',
            name='country_code',
            field=models.CharField(default='+977', max_length=4),
        ),
        migrations.AlterField(
            model_name='contactnum',
            name='mobile_num',
            field=models.CharField(max_length=10),
        ),
    ]
