# Generated by Django 4.0.1 on 2022-01-16 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0003_alter_documentimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='access_road',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 14, 15, 45, 525642)),
        ),
    ]
