# Generated by Django 4.0.1 on 2022-02-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0003_alter_house_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycstatus',
            old_name='kyc_type',
            new_name='kyc_status',
        ),
    ]
