# Generated by Django 4.0.1 on 2022-01-16 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0004_property_access_road_alter_documentimage_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_negitiable',
            new_name='price_negotiable',
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 14, 20, 4, 592633)),
        ),
    ]
