# Generated by Django 4.0.1 on 2022-03-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0004_contactnum_country_code_alter_contactnum_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='province',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='province',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
