# Generated by Django 4.0.1 on 2022-02-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0004_rename_kyc_type_kycstatus_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
