# Generated by Django 4.0.1 on 2022-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0005_house_province_house_url_land_province_land_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='parking',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='house',
            name='bath',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='house',
            name='beds',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='house',
            name='floors',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='house',
            name='kitchen',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='house',
            name='living',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
