# Generated by Django 4.0.1 on 2022-02-28 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0005_alter_facility_facility_alter_propertytype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='p_sale.housetype'),
        ),
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='p_sale.kycstatus'),
        ),
        migrations.AlterField(
            model_name='land',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
