# Generated by Django 4.0.1 on 2022-01-16 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0005_rename_price_negitiable_property_price_negotiable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 16, 14, 36, 29, 503073)),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
