# Generated by Django 4.0.1 on 2022-03-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0006_house_parking_alter_house_bath_alter_house_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
