# Generated by Django 4.0.1 on 2022-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0007_property_created_at_property_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
