# Generated by Django 4.0.1 on 2022-03-31 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0008_alter_house_beds_alter_house_floors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.PROTECT, to='p_sale.kycstatus'),
        ),
    ]
