# Generated by Django 4.0.1 on 2022-01-16 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0008_property_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='p_sale.seller'),
            preserve_default=False,
        ),
    ]
