# Generated by Django 4.0.1 on 2022-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0009_property_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='no_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
