# Generated by Django 4.0.1 on 2022-04-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0009_alter_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_sale.kyc'),
        ),
    ]
