# Generated by Django 4.0.1 on 2022-04-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0010_alter_contactnum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_nums', to='p_sale.kyc'),
        ),
    ]
