# Generated by Django 4.0.1 on 2022-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0011_alter_property_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('vrifying', 'verifying'), ('verified', 'verified')], default='pending', max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('TL', 'Top Listing Rs.23600'), ('pl', 'Premium Listing Rs.17600'), ('FL', 'Featured Listing Rs.9600')], max_length=100),
        ),
    ]
