# Generated by Django 4.0.1 on 2022-04-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0011_alter_contactnum_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactnum',
            old_name='user',
            new_name='kyc_id',
        ),
    ]
