# Generated by Django 4.0.1 on 2022-01-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0012_alter_kyc_status_alter_property_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('vrifying', 'verifying'), ('verified', 'verified')], default='pending', max_length=60),
        ),
    ]
