# Generated by Django 4.0.1 on 2022-04-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0012_rename_user_contactnum_kyc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseownercertificate',
            name='certificate_name',
        ),
        migrations.RemoveField(
            model_name='landownercertificate',
            name='certificate_name',
        ),
    ]
