# Generated by Django 4.0.1 on 2022-01-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0013_alter_kyc_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentImage',
            new_name='AdditionalPropertyImage',
        ),
    ]
