# Generated by Django 4.0.1 on 2022-04-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0013_remove_houseownercertificate_certificate_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='per',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
