# Generated by Django 4.0.1 on 2022-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0014_house_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='on_sale',
        ),
    ]
