# Generated by Django 4.0.1 on 2022-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0015_remove_house_on_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='house',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='land',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
