# Generated by Django 4.0.1 on 2022-04-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0016_alter_house_options_alter_land_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='aana',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='daam',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='paisa',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='ropani',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='aana',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='daam',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='paisa',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='ropani',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
