# Generated by Django 4.0.1 on 2022-01-17 07:34

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0016_alter_contactnum_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalpropertyimage',
            name='document_image',
        ),
        migrations.AddField(
            model_name='additionalpropertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='additionalpropertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='p_sale.property'),
        ),
    ]
