# Generated by Django 4.0.1 on 2022-01-17 07:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0017_remove_additionalpropertyimage_document_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='aana',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, choices=[('Ropani', 'Ropani'), ('Sq,Ft', 'Sq.Ft'), ('Dhur', 'Dhur'), ('Kathha', 'Kathha'), ('Hath', 'Hath'), ('Bigha', 'Bigha')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='daam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='paisa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='ropani',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyownercertificate',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
