# Generated by Django 4.0.1 on 2022-01-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0018_alter_property_aana_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='aana',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='daam',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('TL', 'Top Listing Rs.23600'), ('Pl', 'Premium Listing Rs.17600'), ('FL', 'Featured Listing Rs.9600')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='paisa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ropani',
            field=models.IntegerField(blank=True),
        ),
    ]
