# Generated by Django 4.0.1 on 2022-01-21 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0019_alter_property_aana_alter_property_daam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalpropertyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
