# Generated by Django 4.0.1 on 2022-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0020_alter_additionalpropertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='aana',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='daam',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='paisa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='ropani',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
