# Generated by Django 4.0.1 on 2022-01-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0021_alter_property_aana_alter_property_daam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='aana',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='daam',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='paisa',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='ropani',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
