# Generated by Django 4.0.1 on 2022-01-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_sale', '0022_alter_property_aana_alter_property_daam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bath',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='kitchen',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='living',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
